# Generated by Django 3.1.4 on 2020-12-11 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201211_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
