# Generated by Django 3.1.4 on 2020-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_movies_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='static/thumbnail/'),
            preserve_default=False,
        ),
    ]
